# Generated by Django 4.0.5 on 2022-08-31 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_year', models.IntegerField(blank=True, null=True)),
                ('cleint_nums', models.IntegerField(blank=True, null=True)),
                ('num_projects', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=30, null=True)),
                ('levels', models.CharField(choices=[('Entry', 'Entry'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=50)),
                ('experience_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.experience_field')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('job_title', models.CharField(max_length=30, null=True)),
                ('start_date', models.DateField()),
                ('present', models.BooleanField(blank=True, default=False, null=True)),
                ('end_date', models.DateField()),
                ('text', models.TextField(null=True)),
                ('used_technologies', models.ManyToManyField(null=True, to='main.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=30, null=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.service_category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Project_Images')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('used_technologies', models.ManyToManyField(null=True, to='main.skill')),
            ],
        ),
    ]
